/**
 * DailyStack — AI Match Insight Component
 * Displays AI-generated compatibility explanation
 */

import React from 'react';
import { Sparkles, CheckCircle2, TrendingUp } from 'lucide-react';

interface AIMatchInsightProps {
  insights: string[];
  variant?: 'compact' | 'expanded';
}

// ─── Insight Item ─────────────────────────────────────────────────────────────
const InsightItem: React.FC<{ text: string; type: 'strength' | 'opportunity' }> = ({ text, type }) => (
  <div className="flex items-start gap-3 p-3 rounded-xl bg-[rgba(255,255,255,0.05)]">
    <div className={`w-6 h-6 rounded-full flex items-center justify-center shrink-0 mt-0.5
      ${type === 'strength' ? 'bg-[#22C55E]/20 text-[#22C55E]' : 'bg-[#FFD700]/20 text-[#FFD700]'}`}>
      {type === 'strength' ? (
        <CheckCircle2 size={14} />
      ) : (
        <TrendingUp size={14} />
      )}
    </div>
    <p className="text-sm text-white/90 leading-relaxed">{text}</p>
  </div>
);

// ─── Main AI Match Insight ────────────────────────────────────────────────────
const AIMatchInsight: React.FC<AIMatchInsightProps> = ({ insights, variant = 'compact' }) => {
  if (variant === 'expanded') {
    return (
      <div className="bg-[rgba(13,17,23,0.90)] backdrop-blur-xl rounded-2xl p-4 
        border border-[rgba(255,255,255,0.10)]">
        
        {/* Header */}
        <div className="flex items-center gap-2 mb-4">
          <Sparkles size={18} className="text-[#FFD700]" />
          <h4 className="text-sm font-bold text-white">AI Match Insights</h4>
        </div>

        {/* Insights list */}
        <div className="space-y-3">
          {insights.map((insight, index) => (
            <InsightItem key={index} text={insight} type="strength" />
          ))}
        </div>

        {/* Footer note */}
        <p className="text-[10px] text-[var(--text-muted)] mt-4 leading-relaxed">
          These insights are generated by AI based on your profile compatibility and behavioral patterns.
          Results are updated daily as you interact with the app.
        </p>
      </div>
    );
  }

  // Compact version (for card overlay)
  return (
    <div className="bg-[rgba(13,17,23,0.80)] backdrop-blur-sm rounded-2xl p-4 border border-[rgba(255,255,255,0.08)]">
      <div className="flex items-center gap-2 mb-3">
        <Sparkles size={14} className="text-[#FFD700]" />
        <span className="text-xs font-semibold text-[#FFD700]">Why You Match</span>
      </div>
      <div className="space-y-2">
        {insights.slice(0, 2).map((insight, index) => (
          <p key={index} className="text-xs text-white/80 leading-relaxed flex items-start gap-2">
            <span className="w-1.5 h-1.5 rounded-full bg-[#22C55E] shrink-0 mt-1.5" />
            {insight}
          </p>
        ))}
      </div>
    </div>
  );
};

export default AIMatchInsight;