import React from 'react'
import { render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter } from 'react-router-dom'
import userEvent from '@testing-library/user-event'
import AuthPage from '../app/pages/AuthPageV2'
import { peekOtpFor } from '../mocks/handlers'

test('full OTP flow: send, paste, verify -> success', async () => {
  render(
    <MemoryRouter>
      <AuthPage />
    </MemoryRouter>
  )

  // Enter email and continue
  const emailInput = screen.getByPlaceholderText('name@company.com')
  await userEvent.type(emailInput, 'test+msw@example.com')
  const continueBtn = screen.getAllByRole('button', { name: /continue/i }).find(b => b.getAttribute('type') === 'submit')!
  await userEvent.click(continueBtn)

  // Wait for step 2 UI
  await waitFor(() => expect(screen.getByText(/verification code/i)).toBeInTheDocument())

  // Get the code generated by MSW handler (dev helper)
  const code = peekOtpFor('test+msw@example.com')
  if (!code) throw new Error('No OTP code found for test email')
  expect(code).toHaveLength(6)

  // Type the code into each OTP input
  const inputs = screen.getAllByRole('textbox')
  for (let i = 0; i < code.length; i++) {
    await userEvent.type(inputs[i], code[i])
  }

  // Submit verify
  const verifyBtn = screen.getByRole('button', { name: /create account/i })
  await userEvent.click(verifyBtn)

  // Wait for success UI
  await waitFor(() => expect(screen.getByText(/you're in!/i)).toBeInTheDocument())
})
